name: 问题反馈
description: 反馈一个BUG
title: "[Bug] "
labels: ["bug"]
assignees:
  - totowang-hhh
body:
  - type: markdown
    attributes:
      value: |
        感谢提交问题！很抱歉浪费您的时间……
        注：如果您只是为了催我或联系我而新建一个issue，请停止这么做并直接联系我的邮箱：tt1224@hotmail.com
  - type: checkboxes
    id: terms
    attributes:
      label: 开始前请检查
      description: 请检查以下问题，这有助于我更高效地管理并解决您和他人的反馈。
      options:
        - label: 您已检查且确定没有其他人提出仍未解决的相关问题
          required: true
        - label: 您已尝试过更换版本（更新至最新或回退至x.0.0），但似乎并不起效
          required: true
  - type: input
    id: contact
    attributes:
      label: 联系方式
      description: 我如何联系您来获得更多信息
      placeholder: 例：email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 问题详情
      description: 发生甚么事了！？
      placeholder: 您看到了……
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: tttk版本
      description: 您最初在哪个版本遇到该问题？
      multiple: false
      options:
        - 0.1.0
        - 1.0.0
    validations:
      required: true
  - type: dropdown
    id: version_tested
    attributes:
      label: 已尝试过的版本
      description: 您尝试过哪个（些）版本的tttk并仍然遇到该问题？
      multiple: true
      options:
        - 0.1.0
        - 1.0.0
    validations:
      required: false
  - type: dropdown
    id: system
    attributes:
      label: 系统和版本
      description: 您最初在哪个系统遇到该问题？\n如果您认为您需要留下更详细的信息，请在额外信息中说明。
      multiple: false
      options:
        - Windows 10/11
        - Windows 7 SP1 ~ 8.1
        - Windows 1.0 ~ ME （不支持Python 3）
        - Windows 2000 ~ 7 （不支持Python 3）
        - Mac OS （作者没有该环境）
        - Linux
        - DOS / 命令行Linux / 其他命令行系统 （不支持Python 3和tkinter）
        - Android / iOS / 其余大部分移动端 （不支持tkinter）（需在额外信息中说明具体系统和终端软件）
        - 与此无关，个人猜测此问题存在于所有系统
    validations:
      required: true
  - type: dropdown
    id: system_other
    attributes:
      label: 其他可能出现问题的系统
      description: 您猜测/知道还有哪些系统会遇到该问题？\n如果您认为您需要留下更详细的信息，请在额外信息中说明。
      multiple: true
      options:
        - Windows 10/11
        - Windows 7 SP1 ~ 8.1
        - Mac OS （作者没有该环境）
        - Linux
        - Android / iOS / 其余大部分移动端 （不支持tkinter）
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 相关输出
      description: 请粘贴任何有关的输出至此处，它们会被自动转换为代码格式。
      render: shell
  - type: textarea
    id: other
    attributes:
      label: 附加内容
      description: 如果您还想附上其他信息，请打好小标题附在这里。\n您可以在此处附截图。
      placeholder: 附加内容……
    validations:
      required: false
